step 1: import 必要的库

In [2]:
import pandas as pd

step 2: 使用read_excel阅读excel数据文件

In [4]:
pd.read_excel("fund_data.xls")

,公募基金资产统计,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,更新日期,类别,封闭式,开放式,开放式,开放式,开放式,开放式,开放式,开放式,合计
1,NaN,NaN,NaN,股票基金,混合基金,货币市场基金,债券基金,QDII,其他,开放式合计,NaN
2,2022年07月,基金数量(只),1238.00,1942.00,4358.00,357.00,2024.00,204.00,NaN,8885.00,10123.00
3,2022年07月,份额(亿份),30376.47,18224.21,39304.19,110780.62,42525.32,3224.50,NaN,214058.83,244435.30
4,2022年07月,净值(亿元),32235.76,24073.80,52141.93,110925.42,48327.01,2921.32,NaN,238389.48,270625.24
...,...,...,...,...,...,...,...,...,...,...,...
267,2015年03月,份额(亿份),1402.76,10800.56,7416.54,21627.91,3055.10,663.51,NaN,43563.63,44966.39
268,2015年03月,净值(亿元),1574.58,15805.45,9304.85,21650.32,3534.89,544.27,NaN,50839.79,52414.37
269,2015年02月,基金数量(只),144.00,725.00,425.00,177.00,414.00,92.00,NaN,1833.00,1977.00
270,2015年02月,份额(亿份),1333.91,10833.92,6144.94,21696.26,3217.91,668.46,NaN,42561.50,43895.41
271,2015年02月,净值(亿元),1473.16,14029.83,7123.89,21722.68,3710.23,547.39,NaN,47134.02,48607.18

step 3: 整理数据

In [13]:
pd.read_excel("fund_data.xls", header = 2, index_col = 0)

,Unnamed: 1,Unnamed: 2,股票基金,混合基金,货币市场基金,债券基金,QDII,其他,开放式合计,Unnamed: 10
2022年07月,基金数量(只),1238.00,1942.00,4358.00,357.00,2024.00,204.00,NaN,8885.00,10123.00
2022年07月,份额(亿份),30376.47,18224.21,39304.19,110780.62,42525.32,3224.50,NaN,214058.83,244435.30
2022年07月,净值(亿元),32235.76,24073.80,52141.93,110925.42,48327.01,2921.32,NaN,238389.48,270625.24
2022年06月,基金数量(只),1245.00,1906.00,4312.00,349.00,1996.00,202.00,NaN,8765.00,10010.00
2022年06月,份额(亿份),30706.01,17537.02,39735.04,105855.23,41770.15,3045.80,NaN,207943.24,238649.25
...,...,...,...,...,...,...,...,...,...,...
2015年03月,份额(亿份),1402.76,10800.56,7416.54,21627.91,3055.10,663.51,NaN,43563.63,44966.39
2015年03月,净值(亿元),1574.58,15805.45,9304.85,21650.32,3534.89,544.27,NaN,50839.79,52414.37
2015年02月,基金数量(只),144.00,725.00,425.00,177.00,414.00,92.00,NaN,1833.00,1977.00
2015年02月,份额(亿份),1333.91,10833.92,6144.94,21696.26,3217.91,668.46,NaN,42561.50,43895.41
2015年02月,净值(亿元),1473.16,14029.83,7123.89,21722.68,3710.23,547.39,NaN,47134.02,48607.18

In [50]:
df = pd.read_excel("fund_data.xls", header = 2, index_col = 0)
df.rename(columns={'Unnamed: 1' : '类别', 'Unnamed: 2' : '封闭式', 'Unnamed: 10' : '合计'}, inplace=True)
df

,类别,封闭式,股票基金,混合基金,货币市场基金,债券基金,QDII,其他,开放式合计,合计
2022年07月,基金数量(只),1238.00,1942.00,4358.00,357.00,2024.00,204.00,NaN,8885.00,10123.00
2022年07月,份额(亿份),30376.47,18224.21,39304.19,110780.62,42525.32,3224.50,NaN,214058.83,244435.30
2022年07月,净值(亿元),32235.76,24073.80,52141.93,110925.42,48327.01,2921.32,NaN,238389.48,270625.24
2022年06月,基金数量(只),1245.00,1906.00,4312.00,349.00,1996.00,202.00,NaN,8765.00,10010.00
2022年06月,份额(亿份),30706.01,17537.02,39735.04,105855.23,41770.15,3045.80,NaN,207943.24,238649.25
...,...,...,...,...,...,...,...,...,...,...
2015年03月,份额(亿份),1402.76,10800.56,7416.54,21627.91,3055.10,663.51,NaN,43563.63,44966.39
2015年03月,净值(亿元),1574.58,15805.45,9304.85,21650.32,3534.89,544.27,NaN,50839.79,52414.37
2015年02月,基金数量(只),144.00,725.00,425.00,177.00,414.00,92.00,NaN,1833.00,1977.00
2015年02月,份额(亿份),1333.91,10833.92,6144.94,21696.26,3217.91,668.46,NaN,42561.50,43895.41
2015年02月,净值(亿元),1473.16,14029.83,7123.89,21722.68,3710.23,547.39,NaN,47134.02,48607.18

step 4: 分析数据

In [53]:
df.pivot(columns="类别")

               封闭式                        股票基金                        混合基金  \
类别          份额(亿份)    净值(亿元) 基金数量(只)    份额(亿份)    净值(亿元) 基金数量(只)    份额(亿份)
2015年02月   1333.91   1473.16   144.0  10833.92  14029.83   725.0   6144.94
2015年03月   1402.76   1574.58   146.0  10800.56  15805.45   747.0   7416.54
2015年04月   1408.63   1628.28   146.0  11140.26  17695.30   767.0  10409.72
2015年05月   1482.69   1783.29   147.0  11728.99  20369.76   801.0  17113.14
2015年06月   1446.70   1667.86   149.0  12725.52  17728.17   855.0  20107.49
...            ...       ...     ...       ...       ...     ...       ...
2022年03月  29605.25  31154.38  1208.0  17180.21  22743.22  1855.0  41407.14
2022年04月  29969.87  31539.46  1219.0  17724.36  21783.28  1873.0  40552.15
2022年05月  30099.95  31857.84  1228.0  17623.05  22552.67  1886.0  39755.48
2022年06月  30706.01  32694.87  1245.0  17537.02  24741.65  1906.0  39735.04
2022年07月  30376.47  32235.76  1238.0  18224.21  24073.80  1942.0  39304.19

                               货币市场基金  ...    QDII     其他                 \
类别          净值(亿元) 基金数量(只)     份额(亿份)  ... 基金数量(只) 份额(亿份) 净值(亿元) 基金数量(只)
2015年02月   7123.89   425.0   21696.26  ...    92.0    NaN    NaN     NaN
2015年03月   9304.85   447.0   21627.91  ...    92.0    NaN    NaN     NaN
2015年04月  13121.92   504.0   24957.96  ...    94.0    NaN    NaN     NaN
2015年05月  21315.04   585.0   25317.53  ...    96.0    NaN    NaN     NaN
2015年06月  23072.03   664.0   24093.26  ...    97.0    NaN    NaN     NaN
...            ...     ...        ...  ...     ...    ...    ...     ...
2022年03月  52459.35  4192.0  100031.88  ...   198.0    NaN    NaN     NaN
2022年04月  48807.50  4221.0  108261.41  ...   200.0    NaN    NaN     NaN
2022年05月  50212.95  4266.0  110277.76  ...   202.0    NaN    NaN     NaN
2022年06月  54130.70  4312.0  105855.23  ...   202.0    NaN    NaN     NaN
2022年07月  52141.93  4358.0  110780.62  ...   204.0    NaN    NaN     NaN

              开放式合计                            合计
类别           份额(亿份)     净值(亿元) 基金数量(只)     份额(亿份)     净值(亿元)  基金数量(只)
2015年02月   42561.50   47134.02  1833.0   43895.41   48607.18   1977.0
2015年03月   43563.63   50839.79  1881.0   44966.39   52414.37   2027.0
2015年04月   50505.38   60369.63  1962.0   51914.01   61997.91   2108.0
2015年05月   58236.54   71809.54  2084.0   59719.22   73592.83   2231.0
2015年06月   60939.45   69472.47  2230.0   62386.15   71140.33   2379.0
...             ...        ...     ...        ...        ...      ...
2022年03月  197827.96  219691.18  8461.0  227433.21  250845.56   9669.0
2022年04月  206106.03  223670.85  8542.0  236075.90  255210.32   9761.0
2022年05月  209686.70  230694.36  8644.0  239786.64  262552.19   9872.0
2022年06月  207943.24  235167.94  8765.0  238649.25  267862.81  10010.0
2022年07月  214058.83  238389.48  8885.0  244435.30  270625.24  10123.0

[90 rows x 27 columns]

In [63]:
pivot_df = df.pivot(columns="类别")
pivot_df.to_excel("pivot.xls", encoding='gb2312')

C:\Users\lianb\AppData\Local\Temp\ipykernel_31040\3471675893.py:2: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  pivot_df.to_excel("pivot.xls", encoding='gb2312')