step 1: import 必要的库

In [1]:
import pandas as pd

step 2: 使用read_excel阅读excel数据文件

In [5]:
pd.read_excel("fund_data.xls")
#pd.read_excel("simple_excel_data.xlsx")

,公募基金资产统计,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,更新日期,类别,封闭式,开放式,开放式,开放式,开放式,开放式,开放式,开放式,合计
1,NaN,NaN,NaN,股票基金,混合基金,货币市场基金,债券基金,QDII,其他,开放式合计,NaN
2,2022年07月,基金数量(只),1238.00,1942.00,4358.00,357.00,2024.00,204.00,NaN,8885.00,10123.00
3,2022年07月,份额(亿份),30376.47,18224.21,39304.19,110780.62,42525.32,3224.50,NaN,214058.83,244435.30
4,2022年07月,净值(亿元),32235.76,24073.80,52141.93,110925.42,48327.01,2921.32,NaN,238389.48,270625.24
...,...,...,...,...,...,...,...,...,...,...,...
267,2015年03月,份额(亿份),1402.76,10800.56,7416.54,21627.91,3055.10,663.51,NaN,43563.63,44966.39
268,2015年03月,净值(亿元),1574.58,15805.45,9304.85,21650.32,3534.89,544.27,NaN,50839.79,52414.37
269,2015年02月,基金数量(只),144.00,725.00,425.00,177.00,414.00,92.00,NaN,1833.00,1977.00
270,2015年02月,份额(亿份),1333.91,10833.92,6144.94,21696.26,3217.91,668.46,NaN,42561.50,43895.41
271,2015年02月,净值(亿元),1473.16,14029.83,7123.89,21722.68,3710.23,547.39,NaN,47134.02,48607.18